---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: priv/id_rsa

verifier:
  name: terraform
  reporter: doc
  groups:
    - name: default
      controls:
        - operating_system
        - check_pkg
        - check_website
      hostnames: public_ip
      username: root

suites:
  - name: default
